version: "3.7"

services:
  nginx:
    image: nginx:stable-alpine
    ports:
    - "8080:80"
    volumes:
    - ./default.conf:/etc/nginx/conf.d/default.conf:ro

  backend:
    image: public.ecr.aws/docker/library/golang:1.24-alpine3.22
    volumes:
    - ./main.go:/opt/main.go:ro
    expose:
    - 9000
    command: ["go", "run", "/opt/main.go"]
